import React from "react";
import Text, {Props as TextProps} from "./Text";

// Attention: This file is generated by "yarn icon", do not modify

export enum IconClass {
// {1}
}

interface Props extends TextProps {
    type: IconClass;
}

export default class Icon extends React.PureComponent<Props> {
    render() {
        const {type, style, ...restProps} = this.props;
        // Only normal fontWeight is supported (on Android)
        return (
            <Text style={[style, {fontFamily: "iconfont", fontWeight: "normal"}]} {...restProps}>
                {String.fromCharCode(type)}
            </Text>
        );
    }
}
