import {CurrentUserAJAXResponse, LoginAJAXRequest, LoginAJAXResponse} from "app/type/api";
import {NetworkService} from "app/service/NetworkService";

// Attention: This file is generated by "yarn api", do not modify

export class AccountAJAXWebService {
    static currentUser(): Promise<CurrentUserAJAXResponse> {
        return NetworkService.ajax("GET", "/ajax/currentUser", {}, null);
    }

    static login(request: LoginAJAXRequest): Promise<LoginAJAXResponse> {
        return NetworkService.ajax("PUT", "/ajax/login", {}, request);
    }

    static logout(): Promise<void> {
        return NetworkService.ajax("PUT", "/ajax/logout", {}, null);
    }
}
