import {ListProductResponse, GetProductResponse, CreateProductConfigResponse} from "app/type/api";
import {NetworkService} from "app/service/NetworkService";

// Attention: This file is generated by "yarn api", do not modify

export class ProductAJAXWebService {
    static list(): Promise<ListProductResponse> {
        return NetworkService.ajax("GET", "/ajax/product", {}, null);
    }

    static get(id: string): Promise<GetProductResponse> {
        return NetworkService.ajax("GET", "/ajax/product/:id", {id}, null);
    }

    static getChild(id: string, childId: string): Promise<GetProductResponse> {
        return NetworkService.ajax("GET", "/ajax/product/:id/child/:childId", {id, childId}, null);
    }

    static createConfig(): Promise<CreateProductConfigResponse> {
        return NetworkService.ajax("GET", "/ajax/product/create-config", {}, null);
    }
}
